name = "himstagram"
license = "MIT"
licenselink = "https://github.com/zazzyzeph/himstagram/blob/master/LICENSE"
description = "A single-column Hugo theme designed exclusively for the male body"
homepage = "https://zephnet.biz"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Zephyr Prusinski"
  homepage = "https://zephnet.biz"

